# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BejQnpUs2KEXZ3uSvvuVb4ycfhC3cU5l

Seaborn is a Python data visualization library built on top of Matplotlib that makes it easier to create attractive, informative, and statistical graphics, especially for exploring relationships in complex datasets.
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np



"""Note : Seaborn has some built-in datasets"""

# total bill vs tip dataset
tips = sns.load_dataset("tips")

tips.head()

# setting a theme for the plots
sns.set_theme()

sns.relplot(data = tips, x = "total_bill", y = "tip", col = "time", hue = "smoker", style = "smoker", size = "size")

# load the iris dataset
iris = sns.load_dataset("iris")

iris.head()

"""Scatter Plot"""

sns.scatterplot(data = iris, x = "sepal_length", y = "petal_length", hue = "species")

sns.scatterplot(data = iris, x = "sepal_length", y = "petal_width", hue = "species")

# loading the titanic dataset
titanic = sns.load_dataset("titanic")

titanic.head()

sns.countplot(data = titanic, x = "class")

titanic.shape

sns.countplot(data = titanic, x = "survived")

"""Bar Chart"""

sns.barplot(data = titanic, x = "sex", y = "survived", hue = "class")

# house price dataset
from sklearn.datasets import fetch_california_housing
house_california = fetch_california_housing()
house = pd.DataFrame(house_california.data, columns = house_california.feature_names)
house['PRICE'] = house_california.target
house.head()

"""Distribution Plot"""

sns.distplot(house['PRICE'])

"""Correlation
- Positive
- Negative
"""

# Heat Map

correlation = house.corr()

# Constructing a heat map
plt.figure(figsize = (10, 10))
sns.heatmap(correlation, cbar = True, square = True, fmt = '.1f', annot = True, annot_kws = {'size': 8}, cmap = 'Blues')