# -*- coding: utf-8 -*-
"""Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7qll9AqvLDdwp5qhyGw6rJ-7fKdfPHO
"""

import numpy as np

"""# Creating a Matrix using numpy"""

matrix_1 = np.array([[2, 3],[6, 7]])
print(matrix_1)

matrix_1.shape

matrix_2 = np.array([[10, 35, 45], [50, 64, 80], [20, 15, 90]])
print(matrix_2)

matrix_2.shape

"""# Creating Matrix with Random Values"""

random_matrix = np.random.rand(3,3)
print(random_matrix)

# creating matrix with random integer
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

matrix_3 = np.ones((2,3))
print(matrix_3)

matrix_3 = np.ones((2,3), dtype = int)
print(matrix_3)

matrix_3 = np.ones((10,10), dtype = int)
print(matrix_3)

null_matrix = np.zeros((4,4))
print(null_matrix)

null_matrix = np.zeros((4,4), dtype= int)
print(null_matrix)

"""#Identity Matrix"""

identity_matrix = np.eye(5,5)
print(identity_matrix)

"""# Transpose of a Matrix"""

# Matrix with random integer values
a = np.random.randint(100, size=(4,3))
print(a)

transpose_of_a = np.transpose(a)
print(transpose_of_a)

"""# Matrix Operation

Two matrices are added if they have same shape
"""

# Creating two matrices

A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])
sum = A+B
print(sum)

matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(10, size=(3,3))
print(matrix_1)
print(matrix_2)
sum_of_matrix = matrix_1 + matrix_2
print(sum_of_matrix)

#sub_of_matrix = matrix_1 - matrix_2
sub_of_matrix = np.subtract(matrix_1, matrix_2)
print(sub_of_matrix)

"""Multiplying matrix a scaler"""

x = 5
y =np.random.randint(10, size = (4,3))
print(y)
product = np.multiply(x,y)
print(product)

"""Multiplying 2 matrices"""

# create two matrics with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(10, size=(3,3))
print(matrix_3)
print(matrix_4)
product_of_matrics = np.dot(matrix_3, matrix_4)
print(product_of_matrics)