# -*- coding: utf-8 -*-
"""Vector Operation 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lw1pXdJRLRIoq1AoCnnIxeYotDZ9PYu1

Vector Operations

1. Dot product of two vectors

2. Cross product of two vectors

3. Projection of vector
"""

import numpy as np

a = np.array([2, 3])
b = np.array([4, 4])

a_dot_b = np.dot(a,b)
print(a_dot_b)

c = np.array([40, 20, 35])

d = np.array([53, 24, 68])

c_dot_d = np.dot(c,d)
print(c_dot_d)

"""# Cross Product"""

a_cross_b = np.cross(a,b)
print(a_cross_b)

c_cross_d = np.cross(c,d)
print(c_cross_d)

"""# Projection of "a" vector on "v" vector"""

a = np.array([2, 5])
v = np.array([8, -6])

magnitude_of_v = np.sqrt(sum(v**2))

proj_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2)*v
print(proj_of_a_on_v)

a = np.array([23, 45, 62 ])
v = np.array([45, 82, 67])

magnitude_of_v = np.sqrt(sum(v**2))

proj_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2)*v
print(proj_of_a_on_v)