# -*- coding: utf-8 -*-
"""Vector Opearions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ogDtBurPlQE0jX8QI4jxFWQgIV7sagm

Vector Operations are:
1. Vector Addition
2. Vector Subtraction
3. Multiplying vector by a scaler
4. Angle between 2 vectors
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set() # Give some defult theme for our plot

"""# Plotting a vector"""

plt.quiver(0, 0, 4, 5)
plt.show()

plt.quiver(0, 0, 4, 5, angles='xy', scale_units='xy', scale=1, color = 'b')
plt.xlim(-8, 8)
plt.ylim(-8, 8)
plt.show()

plt.quiver(0, 0, 4, 5, angles='xy', scale_units='xy', scale=1, color = 'b')
plt.quiver(0, 0, -3, -6, angles='xy', scale_units='xy', scale=1, color = 'g')
plt.xlim(-8, 8)
plt.ylim(-8, 8)
plt.show()

"""# Addition of two vectors"""

vector_1 = np.asarray([0, 0, 2, 3])
vector_2 = np.asarray([0, 0, 3, -2])

sum = vector_1 + vector_2
print(sum)

plt.quiver(0, 0,2, 3, angles='xy', scale_units='xy', scale=1, color = 'b')
plt.quiver(0, 0, 3, -2, angles='xy', scale_units='xy', scale=1, color = 'g')
plt.quiver(0, 0, 5, 1, angles='xy', scale_units='xy', scale=1, color = 'r')
plt.xlim(-8, 8)
plt.ylim(-8, 8)
plt.show()

"""# Subtraction of two vectors"""

vector_3 = np.asarray([0, 0, 2, 3])
vector_4 = np.asarray([0, 0, 3, -2])

difference = vector_1 - vector_2
print(difference)

plt.quiver(0, 0, 2, 3, angles='xy', scale_units='xy', scale=1, color = 'b')
plt.quiver(0, 0, 3, -2, angles='xy', scale_units='xy', scale=1, color = 'g')
plt.quiver(0, 0, -1, 5, angles='xy', scale_units='xy', scale=1, color = 'r')
plt.xlim(-8, 8)
plt.ylim(-8, 8)
plt.show()

"""# Multiplying a vector by a scaler"""

vector_5 = np.asarray([0, 0, 2, 3])

vector_6 = 2*vector_5
print(vector_6)

plt.quiver(0, 0, 2, 3, angles='xy', scale_units='xy', scale=1, color = 'b')
plt.quiver(0, 0, 4, 6, angles='xy', scale_units='xy', scale=1, color = 'r')
plt.xlim(-8, 8)
plt.ylim(-8, 8)
plt.show()

vector_7 = np.asarray([0, 0, 2, 3])

vector_8 = -0.5 *vector_5
print(vector_8)

plt.quiver(0, 0, 2, 3, angles='xy', scale_units='xy', scale=1, color = 'b')
plt.quiver(0, 0, -1, -1.5, angles='xy', scale_units='xy', scale=1, color = 'r')
plt.xlim(-8, 8)
plt.ylim(-8, 8)
plt.show()