# -*- coding: utf-8 -*-
"""Label Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTPyp1ECDRYZB9kX01TaDZGud-egz2r0

Label Encoding
   Convert the labels into numeric form
"""

# Importing the dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder

"""Label Encoding of Breast Cancer Dataset"""

# Loading the data from csv file to pandas dataFrame
cancer_data = pd.read_csv('/content/data.csv')

cancer_data.head()

# Finding the count of different labels
cancer_data['diagnosis'].value_counts()

# load the Label encoder function
label_encode = LabelEncoder()

labels = label_encode.fit_transform(cancer_data.diagnosis)

# Appending the labels to the DataFrame
cancer_data['target'] = labels
cancer_data.head()

"""0 -> Benign
1 -> Malignant
"""

cancer_data['target'].value_counts()

"""Label Encoding of iris data"""

# loading the data from csv file to pandas dataFrame
iris_data = pd.read_csv('/content/iris_data.csv')

iris_data.head()

iris_data['Species'].value_counts()

# Loading the label encoder
label_encoder_1 = LabelEncoder()

iris_labels = label_encoder_1.fit_transform(iris_data.Species)

iris_data['target'] = iris_labels

iris_data.head()

iris_data['target'].value_counts()