# -*- coding: utf-8 -*-
"""Missing_Value.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100_mF77f3F2YcrqlqzXpoOBcFD7lWODj

Method to Handle Missing Values
1. Imputation
2. Dropping
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the dataset to a Pandas DataFrame
dataset = pd.read_csv('/content/Placement_Dataset.csv')

dataset.head()

dataset.shape

dataset.isnull().sum()

"""Central Tendencies:
1. Mean
2. Median
3. Mode
"""

# Analyse the distribution of data in the salary
fig, ax = plt.subplots(figsize=(8,8))
sns.distplot(dataset.salary)

"""Replace the missing value with Median Value"""

dataset['salary'].fillna(dataset['salary'].median(),inplace=True)

dataset.isnull().sum()

# Filling missing values with Mean value
#dataset['salary'].fillna(dataset['salary'].mean(),inplace=True)

# Filling missing values with Mode value
#dataset['salary'].fillna(dataset['salary'].mode(),inplace=True)

"""Dropping method"""

salary_dataset = pd.read_csv('/content/Placement_Dataset.csv')

salary_dataset.shape

salary_dataset.isnull().sum()

# Drop the missing values
salary_dataset = salary_dataset.dropna(how='any')

salary_dataset.isnull().sum()

salary_dataset.shape